plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.systemapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.systemapp"
        minSdk 27
        targetSdk 33
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }


    flavorDimensions "cliente"

    productFlavors {

        acuasur {
            dimension "cliente"
            applicationIdSuffix ".acuasur"
            resValue "string", "app_name", "Acuasur"
            buildConfigField "String", "IP_DEF", '"manteliviano.com"'
            buildConfigField "String", "BASE_API", '"/acuasur/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'false'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'false'
        }

        acuacer {
            dimension "cliente"
            applicationIdSuffix ".acuacer"
            resValue "string", "app_name", "Acuacer"
            buildConfigField "String", "IP_DEF", '"manteliviano.com"'
            buildConfigField "String", "BASE_API", '"/appupdate/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'false'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'false'
        }

        altosmangos {
            dimension "cliente"
            applicationIdSuffix ".altosmangos"
            resValue "string", "app_name", "Alto Los Mangos"
            buildConfigField "String", "IP_DEF", '"manteliviano.com"'
            buildConfigField "String", "BASE_API", '"/AquaProgrammerData/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'true'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'false'
        }

        lasirena {
            dimension "cliente"
            applicationIdSuffix ".lasirena"
            resValue "string", "app_name", "La Sirena"
            buildConfigField "String", "IP_DEF", '"manteliviano.com"'
            buildConfigField "String", "BASE_API", '"/AquaProgrammerDataLaSirena/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'false'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'false'
        }

        asovoragine {
            dimension "cliente"
            applicationIdSuffix ".asovoragine"
            resValue "string", "app_name", "Asovoragine"
            buildConfigField "String", "IP_DEF", '"asovoragine.aquaprogrammer.com"'
            buildConfigField "String", "BASE_API", '"/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'false'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'false'
        }

        demo {
            dimension "cliente"
            applicationIdSuffix ".demo"
            resValue "string", "app_name", "Demo"
            buildConfigField "String", "IP_DEF", '"demo.aquaprogrammer.com"'
            buildConfigField "String", "BASE_API", '"/api/"'
            buildConfigField "boolean", "INVERT_LOGO", 'false'
            buildConfigField "boolean", "FACTURACION_SITIO_SOPORTADA", 'false'
            buildConfigField "boolean", "FOTOS_MULTIPLES_SOPORTADA", 'true'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.0'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'androidx.navigation:navigation-fragment:2.5.3'
    implementation 'androidx.navigation:navigation-ui:2.5.3'
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation files('libs/commons-io-2.2.jar')
    implementation files('libs/posprinterconnectandsendsdk.jar')
    implementation files('libs/SDKLib.jar')

}